### PR TITLE
Add Noble support

### PR DESCRIPTION
**Pull request by bruce-riley**
The companion guardian PR is [here](https://github.com/wormhole-foundation/wormhole/pull/4195).

### CODE REVIEW

**Comment by Mikhai56** [comment]
src/constants/chainIcons.ts(270,11): error TS2322: Type 'string' is not assignable to type 'never'.

**Comment by bruce-riley** [comment]
@johnletey is "grand-1" the IBC chain ID for Noble testnet?

**Comment by johnletey** [comment]
That's correct @bruce-riley

**Review by nik-suri — APPROVED** [review]
Looks good to me to merge pending @johnletey's review

**Review by johnletey — APPROVED** [review]
Looks good from our side!

Only question, shouldn't Noble's testnet have a separate Chain ID?

**Comment by bruce-riley** [comment]
@johnletey testnet generally uses the same chain ID as mainnet. The only time they are different is when we have to deploy a second (sometimes parallel) testnet.

**Review by bingyuyap — APPROVED** [review]

**Review by panoel — APPROVED** [review]

**Review by evan-gray — APPROVED** [review]

**Pull request merged**
